export const todos = [
  { task: 'Купить продукты для ужина.', cheked: false, id: 1 },
  { task: 'Помыть посуду.', cheked: false, id: 2 },
  { task: 'Приготовить ужин.', cheked: false, id: 3 },
  { task: 'Постирать белье.', cheked: false, id: 4 },
  { task: 'Убрать в комнате.', cheked: false, id: 5 },
  { task: 'Выгулять собаку.', cheked: false, id: 6 },
  { task: 'Почитать книгу.', cheked: false, id: 15 },
  { task: 'Посмотреть фильм.', cheked: false, id: 7 },
  { task: 'Заняться спортом.', cheked: false, id: 8 },
  { task: 'Купить продукты для ужина.', cheked: false, id: 9 },
  { task: 'Попробовать новый рецепт.', cheked: false, id: 10 },
  { task: 'Посетить музей.', cheked: false, id: 11 },
  { task: 'Сходить в кино.', cheked: false, id: 12 },
  { task: 'Научиться новому навыку.', cheked: false, id: 13 },
  { task: 'Завести новое хобби.', cheked: false, id: 14 },
]
